name: Build and Push Docker Image For CDC

on:
  push:
    branches:
      - main
    paths:
      - 'cdc-service/**' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inspect builders
        run: docker buildx ls  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_GITHUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./cdc-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/droiddevgeeks/cdc-service:latest